### ISSUE TITLE
Support attributed titles for menu items

### ISSUE THREAD

**Issue by LeoNatan** [AbeWang/AWNavigationMenuItem#1]
Cool project!

A small enhancement idea: consider adding support for optional attributed strings support. This way, it would be possible to have a more personalized menu, as well as image support (through `NSTextAttachment`)

It can work just like UIKit implementation; if the delegate implements the attributed string version of the method, the result of that is used, otherwise there is a fallback to the normal string version.

**Comment by AbeWang** [comment]
Hi Natan,

Thanks for your suggestion!! I'll enhance my menu item to support attributed titles and refactor my code next week :)

**Comment by AbeWang** [comment]
AWNavigationMenuItem now also supports attributed titles!!
Thanks Natan 👍
